server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Para que las imágenes carguen bien
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }
}